name: Deploy Python project to Azure Function App - azure-db-cron-agent

on:
  push:
    branches:
      - main
  workflow_dispatch:

env:
  AZURE_FUNCTIONAPP_PACKAGE_PATH: '.'  # adjust if your function code is in a subdirectory
  PYTHON_VERSION: '3.11'

jobs:
  deploy:
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Login to Azure
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZUREAPPSERVICE_CLIENTID_9772152AAC804D34ABBE4744BDC8184B }}
          tenant-id: ${{ secrets.AZUREAPPSERVICE_TENANTID_0E933E9B711C427D899C722E55BBDE13 }}
          subscription-id: ${{ secrets.AZUREAPPSERVICE_SUBSCRIPTIONID_1185E5C657E64801833A51312DB5DB76 }}

      - name: Deploy to Azure Functions using Oryx
        uses: Azure/functions-action@v1
        with:
          app-name: 'azure-db-cron-agent'
          slot-name: 'Production'
          enable-oryx-build: true
          package: ${{ env.AZURE_FUNCTIONAPP_PACKAGE_PATH }}
